// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwNdOVppRuv0KrJO7rbTlCfEducoODIyI',
    appId: '1:942865886793:android:69af9a8c48a1ffcd985998',
    messagingSenderId: '942865886793',
    projectId: 'travelapp-d7fdd',
    storageBucket: 'travelapp-d7fdd.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmEgPps4zTMhNUnbEVtk-6-smdCm1k2qc',
    appId: '1:942865886793:web:470ca538fca373ec985998',
    messagingSenderId: '942865886793',
    projectId: 'travelapp-d7fdd',
    authDomain: 'travelapp-d7fdd.firebaseapp.com',
    storageBucket: 'travelapp-d7fdd.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2Ox4fJwm3J9MsOxTBE3OlfHATtoo_gsI',
    appId: '1:942865886793:ios:4f70a8f3b744da8f985998',
    messagingSenderId: '942865886793',
    projectId: 'travelapp-d7fdd',
    storageBucket: 'travelapp-d7fdd.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2Ox4fJwm3J9MsOxTBE3OlfHATtoo_gsI',
    appId: '1:942865886793:ios:4f70a8f3b744da8f985998',
    messagingSenderId: '942865886793',
    projectId: 'travelapp-d7fdd',
    storageBucket: 'travelapp-d7fdd.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmEgPps4zTMhNUnbEVtk-6-smdCm1k2qc',
    appId: '1:942865886793:web:f1bf5a4d2946acb9985998',
    messagingSenderId: '942865886793',
    projectId: 'travelapp-d7fdd',
    authDomain: 'travelapp-d7fdd.firebaseapp.com',
    storageBucket: 'travelapp-d7fdd.appspot.com',
  );

}